version: "3.7"

services:
  nginx.service:
    image: nginx:1.19.0
    container_name: nginx_service
    restart: always
    ports:
      - "80:80"
      - "81:81" # web ui port
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  simplecoreapi_a_service:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro # local dev certificates
  simplecoreapi_b_service:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro # local dev certificates
networks:
  default:
    name: nginx_network
    driver: bridge
