version: "3.7"

services:
  haproxy_service:
    image: haproxy:2.1.4
    container_name: haproxy_service
    restart: always
    ports:
      - "80:80"
      - "81:81" # web ui port
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  simplecoreapi_service:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro # local dev certificates
networks:
  default:
    name: haproxy.network
    driver: bridge
