scrape_configs:
  # Scape product service API
  - job_name: "apiinsights"
    metrics_path: /prometheus
    consul_sd_configs:
      - server: "consul_service:8500"
        services:
          - apiinsights
        refresh_interval: 30s

  # Scrape Prometheus itself every 5 seconds.
  - job_name: "prometheus"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape consul
  - job_name: "consulserver"
    metrics_path: /v1/agent/metrics
    params:
      format: ["prometheus"]
    scrape_interval: 15s
    static_configs:
      - targets: ["consul_service:8500"]

  # Scrape docker host
  - job_name: "docker_host"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9100"]
