@host = http://localhost:5000
@securehost = https://localhost:5001
@traefikdash = http://localhost:8081
@proxy = http://localhost
@secureproxy = https://localhost

### Local API Root Request
GET {{host}}
Accept: application/json

### Local API Path Request
GET {{host}}/api
Accept: application/json

### API Request proxied through traefix container
GET {{proxy}}/api
Accept: application/json
HOST: simpleapi.service

### API Request proxied through traefix w/ TLS termination
GET {{secureproxy}}/api
Accept: application/json
HOST: simpleapi.service